services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ${PWD}:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # コンテナを起動し続けるためのコマンド
    command: sleep infinity
